SlugOS: commit 5.3-beta

diff --git a/trunk/slugos/openembedded/packages/gpsd/files/gpsd b/trunk/slugos/openembedded/packages/gpsd/files/gpsd
--- a/trunk/slugos/openembedded/packages/gpsd/files/gpsd
+++ b/trunk/slugos/openembedded/packages/gpsd/files/gpsd
@@ -6,15 +6,14 @@
 # description: Gpsd manages access to a serial- or USB-connected GPS
 # processname: gpsd
 
-# If you must specify a non-NMEA driver, uncomment and modify the next line
-#GPSD_OPTS=
-GPS_DEV="/dev/ttyS3"
-
 # Source function library.
 #. /etc/rc.d/init.d/functions
 
 RETVAL=0
+DAEMON=/usr/sbin/gpsd
 prog="gpsd"
+
+test -f /etc/default/$prog && . /etc/default/$prog
 
 start() {
 	# Start daemons.
@@ -31,31 +30,35 @@ start() {
 	# 2. We don't need all the logging crud that daemon/initlog sets
 	# up -- gpsd does its own syslog calls.
 	#
+	
+	if test -x /etc/init.d/gps-hardware
+	then
+		if ! ( /etc/init.d/gps-hardware status | grep -q "ready" )
+		then
+			/etc/init.d/gps-hardware start
+		fi
+	fi
+	
 	if [ -e "${GPS_DEV}" ]
 	then
-	    gpsd ${GPSD_OPTS} -p ${GPS_DEV}
-	     echo "success"
+	    start-stop-daemon -S -x ${DAEMON} -- ${GPSD_OPTS} ${GPS_DEV}
+	    echo "success"
 	else
 	    # User needs to symlink ${GPS_DEV} to the right thing
-	    echo "No ${GPS_DEV} device, aborting gpsd startup."
+	    echo "No ${GPS_DEV} GPS device, aborting gpsd startup. Check /etc/default/$prog"
 	fi
 	RETVAL=$?
 	echo
-	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/gpsd
 	return $RETVAL
 }
 
 stop() {
 	# Stop daemons.
 	echo -n "Shutting down $prog: "
-        killall gpsd
+        start-stop-daemon -K -x ${DAEMON}
 #        killproc gpsd
 	RETVAL=$?
 	echo
-	if [ $RETVAL -eq 0 ]
-	then
-	    rm -f /var/lock/subsys/gpsd;
-	fi
 	return $RETVAL
 }
 
@@ -72,19 +75,12 @@ case "$1" in
 	start
 	RETVAL=$?
 	;;
-  condrestart)
-	if [ -f /var/lock/subsys/gpsd ]; then
-	    stop
-	    start
-	    RETVAL=$?
-	fi
-	;;
   status)
 #	status gpsd
 #	RETVAL=$?
 	;;
   *)
-	echo "Usage: $0 {start|stop|restart|condrestart|status}"
+	echo "Usage: $0 {start|stop|restart|status}"
 	exit 1
 esac
 
diff --git a/trunk/slugos/openembedded/packages/slugos-init/files/functions b/trunk/slugos/openembedded/packages/slugos-init/files/functions
--- a/trunk/slugos/openembedded/packages/slugos-init/files/functions
+++ b/trunk/slugos/openembedded/packages/slugos-init/files/functions
@@ -21,7 +21,9 @@ machine(){
 	*Avila*)	echo avila;;
 	*Loft*)		echo loft;;
 	*NAS?100d*)	echo nas100d;;
+	*DSM?G600*)	echo dsmg600;;
 	*NSLU2*)	echo nslu2;;
+	*FSG?3*)	echo fsg3;;
 	*)		echo unknown;;
 	esac
 }
@@ -171,6 +173,7 @@ checkmount(){
 	# basic test for init (the kernel will try to load this)
 	# but require a shell in bin/sh too
 	test	\( -d "$1/mnt" \) -a \
+		\( -d "$1/dev" \) -a \
 		\( -x "$1/bin/sh" -o -h "$1/bin/sh" \) -a \
 		\( -x "$1/usr/sbin/chroot" -o -h "$1/usr/sbin/chroot" -o \
 		   -x "$1/sbin/chroot" -o -h "$1/sbin/chroot" \) -a \
@@ -179,21 +182,35 @@ checkmount(){
 		   -x "$1/bin/init" -o -h "$1/bin/init" \)
 }
 #
+# minimaldevnodes "mountpoint"
+#  tests an already mounted mountpoint to see if a very minimal
+#  set of devices exists or can be created in dev, and returns
+#  failure if not.  This is required for booting to an nfsroot
+#  with an empty dev directory, as commonly occurs when the rootfs
+#  is created from a tar.gz image.  This is also required for mdev.
+minimaldevnodes(){
+	[ -c "$1/dev/console" ] || mknod -m 600 "$1/dev/console" c 5 1 || return 1
+	[ -c "$1/dev/null"    ] || mknod -m 666 "$1/dev/null"    c 1 3 || return 1
+	[ -c "$1/dev/tty0"    ] || mknod -m 644 "$1/dev/tty0"    c 4 0 || return 1
+	return 0
+}
+#
 # swivel "new root" "old root"
 #  NOTE: the arguments must be paths relative to /, bad things
 #  will happen if the arguments themselves start with /
 #  Pivot to a new root.  This does all the fancy pivot_root stuff
-#  including closing streams and does a umount /proc - it doesn't
-#  matter if this fails (failure codes are ignored), but if /proc
-#  was mounted it must be restored by the caller on return.
-#  Normally this function never returns!
+#  including closing streams and does a umount of /proc and /sys -
+#  it doesn't matter if this fails (failure codes are ignored),
+#  but if /proc and/or /sys was mounted it must be restored by the
+#  caller on return.  Normally this function never returns!
 #  On return 0,1,2 are connected to /dev/console - this may not
 #  have been true before!
 swivel(){
 	cd "$1"
 	exec <&- >&- 2>&-
-	# This is just-in-case the called mounted /proc and was
-	# unable to close it because of the streams
+	# This is just-in-case the caller mounted either /proc or
+	# /sys, and was unable to close them
+	umount /sys  2>/dev/null
 	umount /proc 2>/dev/null
 	if pivot_root . "$2"
 	then
@@ -225,11 +242,17 @@ swivel(){
 			test -x sbin/init && exec sbin/init
 			test -x etc/init && exec etc/init
 			test -x bin/init && exec bin/init
+			# Problematic failure! The chroot worked, but the
+			# exec failed.  Nothing to do but blink the LEDs.
+			# (Use a wildcard because the LED names depend on
+			# the version of the kernel in use.)
 			mount -t sysfs sysfs /mnt
-			echo -n timer >/mnt/class/leds/ready/trigger
-			echo -n timer >/mnt/class/leds/status/trigger
-			echo -n 80 >/mnt/class/leds/ready/frequency
-			echo -n 80 >/mnt/class/leds/status/frequency
+			for i in /mnt/class/leds/*[ready\|status]
+			do
+				echo -n timer >$i/trigger
+				echo -n 60    >$i/delay_on
+				echo -n 30    >$i/delay_off
+			done
 			umount /mnt
 			sync;sync;sync
 			exit 1"
@@ -272,6 +295,8 @@ ifup(){
 	if test "$(config boot)" != static
 	then
 		test -n "$hostname" && HOSTNAME="-H $hostname"
+		# Pause a moment in case link negotiation takes a while
+		sleep 3
 		# The script writes the required shell variable assignments
 		# to file descriptor 9
 		eval $(udhcpc -i "$iface" -n -q -r "$ip" $HOSTNAME -s /boot/udhcpc.script 9>&1 >/dev/null)
diff --git a/trunk/slugos/openembedded/packages/slugos-init/files/sysconf b/trunk/slugos/openembedded/packages/slugos-init/files/sysconf
--- a/trunk/slugos/openembedded/packages/slugos-init/files/sysconf
+++ b/trunk/slugos/openembedded/packages/slugos-init/files/sysconf
@@ -8,35 +8,45 @@
 # to load these functions!)
 test "$1" != sysconf && . /etc/default/functions
 
+case "$(machine)" in
+nslu2)
+	kpart="Kernel"
+	syspart="SysConf"
+	ffspart="Flashdisk";;
+*)
+	kpart="kernel"
+	syspart="sysconfig"
+	ffspart="filesystem";;
+esac
 #
 # sysconf_valid
 #  return true if the SysConf partition exists and seems to be
 #  potentially valid (it starts with a reasonable length).
 sysconf_valid(){
 	local sysdev
-	sysdev="$(mtblockdev SysConf)"
+	sysdev="$(mtblockdev $syspart)"
 	test -n "$sysdev" -a -b "$sysdev" &&
 		devio "<<$sysdev" '!! b.10>s32768<&!'
 }
 
 #
 # sysconf_read [prefix]
-#  read the SysConf partition (if present) writing the result into
+#  read the $syspart partition (if present) writing the result into
 #  /etc/default/sysconf, if the result is empty it will be removed.
 sysconf_read(){
 	local sysdev sedcmd mac config_root
 	config_root="$1"
 	rm -f /tmp/sysconf.new
-	sysdev="$(mtblockdev SysConf)"
+	sysdev="$(mtblockdev $syspart)"
 	if sysconf_valid
 	then
-		# Read the defined part of SysConf into /etc/default/sysconf.
-		# SysConf has lines of two forms:
+		# Read the defined part of $syspart into /etc/default/sysconf.
+		# $syspart has lines of two forms:
 		#
 		#  [section]
 		#  name=value
 		#
-		# In practice SysConf also contains other stuff, use the command:
+		# In practice $syspart also contains other stuff, use the command:
 		#
 		#  devio '<</dev/mtd1;cpb'
 		#
@@ -81,7 +91,7 @@ sysconf_read(){
 
 #
 # sysconf_default [prefix]
-#  Provde a default /etc/default/sysconf when there is no SysConf partition,
+#  Provde a default /etc/default/sysconf when there is no $syspart partition,
 #  or when it is invalid, this function will read from an existing sysconf,
 #  copying the values into the new one.
 # sysconf_line tag config-tag
@@ -228,7 +238,7 @@ sysconf_save_conffiles(){
 	}
 	#
 	(	cd "$ffsdir"
-		find etc/*.conf $(sed 's!^/!!' usr/lib/ipkg/info/*.conffiles) ! -type d -newer etc/.configured -print |
+		find etc/*.conf $(sed 's!^/!!' usr/lib/opkg/info/*.conffiles) ! -type d -newer etc/.configured -print |
 			sed 's/^/diff /'
 		exec sed 's/#.*$//;/^[ 	]*$/d' etc/default/conffiles
 	) | sed 's!^/*!!' |
@@ -371,7 +381,7 @@ sysconf_restore_conffiles(){
 			else
 				echo "sysconf_restore_conffiles: $file: timestamp copy failed (ignored)" >&2
 			fi
-		elif test -h "$saved/file" -o -h "$ffsdir/$file"
+		elif test -h "$saved/$file" -o -h "$ffsdir/$file"
 		then
 			# new or old symbolic link
 			if test -h "$saved/$file" -a -h "$ffsdir/$file" &&
@@ -386,7 +396,7 @@ sysconf_restore_conffiles(){
 					echo "$file"
 					echo "$file" >&3;;
 				diff)	# need user input
-					if sysconf_verify_link "$file" <>/dev/tty >&0 2>&0
+					if sysconf_verify_link "$file" </dev/tty >/dev/tty 2>&1
 					then
 						echo "$file"
 						echo "$file" >&3
@@ -410,7 +420,7 @@ sysconf_restore_conffiles(){
 					echo "$file"
 					echo "$file" >&3;;
 				diff)	# the files are different, get user input
-					if sysconf_verify "$file" <>/dev/tty >&0 2>&0
+					if sysconf_verify "$file" </dev/tty >/dev/tty 2>&1
 					then
 						echo "$file"
 						echo "$file" >&3
@@ -446,7 +456,7 @@ sysconf_test_restore(){
 		elif test "$file" = "etc/.configured"
 		then
 			: # special handling
-		elif test -h "$saved/file" -o -h "$ffsdir/$file"
+		elif test -h "$saved/$file" -o -h "$ffsdir/$file"
 		then
 			# new or old symbolic link
 			if test -h "$saved/$file" -a -h "$ffsdir/$file" &&
@@ -477,13 +487,14 @@ sysconf_test_restore(){
 
 #
 # sysconf_save
-#  save the system configuration to SysConf - SysConf must exist and
+#  save the system configuration to $syspart - $syspart must exist and
 #  there must be a writeable device for it.
 sysconf_save(){
-	local sysdev ffspart ffsdev ffsdir saved list size status
-	ffspart=Flashdisk
+	local sysdev ffsdev ffsdir saved list size status
 	ffsdev="$(mtblockdev $ffspart)"
-	sysdev="$(mtblockdev SysConf)"
+	[ -n "$ffsdev" ] || \
+	ffsdev="$(mtblockdev rootfs)"
+	sysdev="$(mtblockdev $syspart)"
 	status=1
 	if test -n "$sysdev" -a -b "$sysdev" -a -n "$ffsdev" -a -b "$ffsdev"
 	then
@@ -535,7 +546,7 @@ sysconf_save(){
 		size="$(devio "<</tmp/sysconf.$$" 'pr$')"
 		gzip -9 <"$saved" >>/tmp/sysconf.$$
 		#
-		# more cleanup, then try to write the new sysconf to SysConf
+		# more cleanup, then try to write the new sysconf to $syspart
 		# the format is a 4 byte big-endian length then the text data
 		# if the data won't fit exit with error code 7
 		rm "$saved" "$list"
@@ -549,26 +560,26 @@ sysconf_save(){
 		0)	echo " done" >&2
 			status=0;;
 		1)	echo " failed" >&2
-			echo " SysConf could not be written (no changes made)" >&2;;
+			echo " $syspart could not be written (no changes made)" >&2;;
 		3)	echo " failed" >&2
-			echo " SysConf partially written, you may want to reset it" >&2;;
+			echo " $syspart partially written, you may want to reset it" >&2;;
 		7)	echo " failed" >&2
-			echo " SysConf is too small: $size bytes required" >&2
+			echo " $syspart is too small: $size bytes required" >&2
 			echo " No change made" >&2;;
 		*)	echo " failed" >&2
-			echo " Internal error writing SysConf" >&2;;
+			echo " Internal error writing $syspart" >&2;;
 		esac
 		#
 		rm -f /tmp/sysconf.$$
 	else
-		echo "sysconf save: SysConf or $ffspart partition not found" >&2
-		echo " A RedBoot partition named 'SysConf' must exist in the system" >&2
+		echo "sysconf save: $syspart or $ffspart partition not found" >&2
+		echo " A RedBoot partition named '$syspart' must exist in the system" >&2
 		echo " flash memory for this command to work, and there must be a" >&2
 		echo " block device to access this partition (udev will normally" >&2
 		echo " create this automatically.  The flash partition contents must" >&2
 		echo " also be accessible in a partition called '$ffspart'" >&2
 		echo
-		echo " To create the SysConf partition use the 'fis create' command" >&2
+		echo " To create the $syspart partition use the 'fis create' command" >&2
 		echo " in the RedBoot boot loader, it is sufficient to make the" >&2
 		echo " partition one erase block in size unless you have substantially" >&2
 		echo " increased the size of the files listed in /etc/default/conffiles" >&2
@@ -579,7 +590,7 @@ sysconf_save(){
 
 #
 # sysconf_restore [auto]
-#  restore previously saved configuration information from SysConf
+#  restore previously saved configuration information from $syspart
 sysconf_restore_error(){
 	local root
 	root="$1"
@@ -589,7 +600,7 @@ sysconf_restore_error(){
 		test -n "$1" && echo "$*"
 		echo
 		echo "The configuration of this machine has been reinitialised using the values"
-		echo "from /etc/default/sysconf, however configuration files saved in the SysConf"
+		echo "from /etc/default/sysconf, however configuration files saved in the $syspart"
 		echo "partition have not been restored."
 		echo
 		echo "You can restore these files by correcting any reported errors then running"
@@ -597,13 +608,13 @@ sysconf_restore_error(){
 		echo "  sysconf restore"
 		echo
 		echo "from the command line.  This will completely reinitialise the configuration"
-		echo "using the information in the SysConf partition."
+		echo "using the information in the $syspart partition."
 	} >"$root/etc/motd"
 	cat "$root/etc/motd" >&2
 }
 #
 sysconf_restore(){
-	local sysdev ffspart ffsdev ffsdir saved restore size status sysconf_noninteractive config_root
+	local sysdev ffsdev ffsdir saved restore size status sysconf_noninteractive config_root
 
 	# if set this means 'do no diff' - this avoids the code above which
 	# would open /dev/tty and therefore allows this stuff to be done from
@@ -611,9 +622,10 @@ sysconf_restore(){
 	sysconf_noninteractive=
 	test "$1" = auto && sysconf_noninteractive=1
 
-	ffspart=Flashdisk
 	ffsdev="$(mtblockdev $ffspart)"
-	sysdev="$(mtblockdev SysConf)"
+	[ -n "$ffsdev" ] || \
+	ffsdev="$(mtblockdev rootfs)"
+	sysdev="$(mtblockdev $syspart)"
 	status=1
 	if test -n "$sysdev" -a -b "$sysdev" -a -n "$ffsdev" -a -b "$ffsdev" &&
 		sysconf_valid
@@ -634,7 +646,7 @@ sysconf_restore(){
 			exit 1
 		}
 		#
-		# first restore the SysConf section
+		# first restore the $syspart section
 		sysconf_read "$ffsdir" || sysconf_default "$ffsdir"
 		#
 		# now use this to regenerate the system files
@@ -653,6 +665,8 @@ sysconf_restore(){
 			#
 			mkdir "$saved" || {
 				sysconf_restore_error "$ffsdir" "$saved: failed to create temporary directory"
+				umount "$ffsdir" && rmdir "$ffsdir" ||
+					echo "$0: $ffsdir: temporary directory cleanup failed" >&2
 				return 1
 			}
 			#
@@ -666,6 +680,8 @@ sysconf_restore(){
 			) || {
 				rm -rf "$saved"
 				sysconf_restore_error "$ffsdir" "$saved: cpio -i failed"
+				umount "$ffsdir" && rmdir "$ffsdir" ||
+					echo "$0: $ffsdir: temporary directory cleanup failed" >&2
 				return 1
 			}
 			# either there must be no 'diff' files or it must
@@ -735,9 +751,9 @@ examined before restoration"
 			echo "$0: $ffsdir: temporary directory cleanup failed" >&2
 		status=0
 	else
-		echo "sysconf restore: SysConf or $ffspart partition not found" >&2
+		echo "sysconf restore: $syspart or $ffspart partition not found" >&2
 		echo " You must have used 'sysconf save' to save configuration data" >&2
-		echo " into the SysConf partition before using this command.  The command" >&2
+		echo " into the $syspart partition before using this command.  The command" >&2
 		echo " will restore the configuration data to the flash root partition" >&2
 		echo " named '$ffspart' - this must also be accessible." >&2
 	fi
@@ -751,12 +767,12 @@ examined before restoration"
 sysconf_help(){
 	#     -------------------------------------------------------------------------------
 	echo "sysconf: usage: sysconf read|default|reload|save|restore" >&2
-	echo " read:    the current SysConf partition is read into /etc/default/sysconf" >&2
+	echo " read:    the current $syspart partition is read into /etc/default/sysconf" >&2
 	echo " default: a default /etc/default/sysconf is created" >&2
 	echo " reload:  system configuration files are recreated from /etc/default/sysconf" >&2
 	echo " save:    /etc/default/sysconf and the files listed in /etc/default/conffiles" >&2
-	echo "          are written to the SysConf partition" >&2
-	echo " restore: the configuration information in the SysConf partition saved by" >&2
+	echo "          are written to the $syspart partition" >&2
+	echo " restore: the configuration information in the $syspart partition saved by" >&2
 	echo "          'sysconf save' is restored" >&2
 }
 
